### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cla7aye15I4nd** [cla7aye15I4nd/camp-experiment#1]
- [ ] Performance
    - [ ] Spec2017
        - [ ] Native
            - [ ] Memory Overhead
            - [x] Runtime Overhead
        - [ ] ASan
            - [ ] Memory Overhead
            - [x] Runtime Overhead
        - [ ] Camp
            - [ ] Memory Overhead
            - [x] Runtime Overhead
        - [x] Pacmem
            - [x] Memory Overhead
            - [x] Runtime Overhead
    - [ ] Spec2006
        - [ ] Native
            - [ ] Memory Overhead
            - [x] Runtime Overhead
        - [ ] ASan
            - [ ] Memory Overhead
            - [x] Runtime Overhead
        - [ ] Camp
            - [ ] Memory Overhead
            - [x] Runtime Overhead
        - [x] Pacmem
            - [x] Memory Overhead
            - [x] Runtime Overhead
- [ ] Security
    - [ ] Juliet
        - [ ] [CWE121] Stack-based Buffer Overflow
        - [ ] [CWE122] Heap-based Buffer Overflow
        - [ ] [CWE124] Buffer Underwrite
        - [ ] [CWE126] Buffer Overread
        - [ ] [CWE127] Buffer Underread
        - [ ] [CWE415] Double Free
        - [ ] [CWE416] Use After Free 
        - [ ] [CWE476] NULL Pointer Dereference
        - [ ] [CWE761] Invalid Free
    - [ ] Exploit
